<div class="row">
					<div class="col-sm-3 col-xs-12">
						<div class="form-group">
						    <select class="form-control" id="exampleSelect1">
						      <option>ngành 1</option>
						      <option>ngành 2</option>
						      <option>ngành 3</option>
						      <option>ngành 4</option>
						      <option>ngành 5</option>
						    </select>
						  </div>
					</div>
					<div class="col-sm-8 col-xs-12">
						
					</div>
			</div>